version: '3'

services:
  fastapi:
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017"
    networks:
      - mynetwork

networks:
  mynetwork:
